# Generated by Django 4.0.4 on 2022-12-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_page',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('In Stock', 'Còn Hàng'), ('Out of Stock', 'Hết Hàng')], max_length=100, null=True),
        ),
    ]
