# Generated by Django 4.0.4 on 2022-12-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product',
            new_name='product_re',
        ),
    ]
