# Generated by Django 4.0.4 on 2022-12-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_product_reviews_product_re'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
    ]
