# Generated by Django 4.0.4 on 2022-12-24 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(default=-1992, max_length=100),
            preserve_default=False,
        ),
    ]
